// Bundles the app kit sources (src/lib/app-kit/kit.css, kit.js) into src/lib/app-kit.generated.ts, so the Worker
// can inline them into every built app without a filesystem. Run after editing either source: node scripts/build-kit.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const css = fs.readFileSync(path.join(root, 'src/lib/app-kit/kit.css'), 'utf8').trim();
// Light minification: whole-line comments and indentation go; the code itself is left exactly as written (no string is ever touched).
const js = fs.readFileSync(path.join(root, 'src/lib/app-kit/kit.js'), 'utf8').split('\n')
  .map(l => l.replace(/^\s+/, ''))
  .filter(l => l && !/^\/\/(?!.*['"`])/.test(l) && !/^\/\*[^*]*\*\/$/.test(l) && !/^\/\*\*.*\*\/$/.test(l))
  .join('\n').trim();
if (/<\/script/i.test(js) || /<\/style/i.test(css)) throw new Error('The kit sources must not contain closing script or style tags');
const out = `// Generated by scripts/build-kit.mjs from src/lib/app-kit/kit.css and kit.js. Do not edit by hand.
export const KIT_CSS = ${JSON.stringify(css)};
export const KIT_JS = ${JSON.stringify(js)};
`;
fs.writeFileSync(path.join(root, 'src/lib/app-kit.generated.ts'), out);
console.log(`app kit bundled: css ${(css.length / 1024).toFixed(1)} KB, js ${(js.length / 1024).toFixed(1)} KB`);
