import '../globals.css'; // site styles load only on these pages; the app under /app has its own
import { SiteNav, SiteFooter } from '@/components/SiteNav';
import { viewer } from '@/lib/viewer';

// Rendered per request: the nav reflects the signed-in state, which comes from the session cookie.
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Privacy' };
export default async function Privacy() {
  const v = await viewer();
  return (<><SiteNav signedIn={!!v} /><main className="wrap prose">
    <h1>Privacy</h1>
    <p>This is a starting point, not legal advice. Have it reviewed before launch.</p>
    <h2>What we store</h2><p>Your account details from sign-in (name, email), the questions you ask and the answers you receive, your Spaces, your usage counters, and your identity graph: the topics, entities, goals, expertise levels and answer-style preferences that Ricorsa infers from your own questions.</p>
    <h2>How the identity graph is used</h2><p>The graph is folded into the prompts sent on your behalf so answers fit what you are working on. It is never shared with other users, never sold, and never used to train models. You can pause learning, forget any node, export the whole graph, or reset it at any time from the Graph page.</p>
    <h2>Processors</h2><p>Answers are generated by Moonshot AI (Kimi); the relevant question text, the retrieved web results and your profile summary are sent to Moonshot AI to produce each answer. Live web results come from Brave Search, which receives the search queries only. Files you attach to a question are read into text on our servers (plain text, code, PDFs, Word, Excel and PowerPoint); scanned documents, images and older binary formats go through Moonshot AI's file extraction service, where the upload is deleted as soon as its text has been read. Only that text is kept, with the thread it was used in, and it is deleted with the thread. Your data is stored on Cloudflare. Sign-in is handled by Auth0 and payments by PayPal; we never see your card or bank details.</p>
    <h2>Your rights</h2><p>Export everything from your Account page. Deleting your account removes your data from our systems and cancels any subscription.</p>
  </main><SiteFooter /></>);
}
