import '../globals.css'; // site styles load only on these pages; the app under /app has its own
import { SiteNav, SiteFooter } from '@/components/SiteNav';
import { viewer } from '@/lib/viewer';

// Rendered per request: the nav reflects the signed-in state, which comes from the session cookie.
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Privacy' };
export default async function Privacy() {
  const v = await viewer();
  return (<><SiteNav signedIn={!!v} /><main className="wrap prose">
    <h1>Privacy</h1>
    <p>This is a starting point, not legal advice. Have it reviewed before launch.</p>
    <h2>What we store</h2><p>Your account details from sign-in (name, email), the questions you ask and the answers you receive, your Spaces, your usage counters, and your identity graph: the topics, entities, goals, expertise levels and answer-style preferences that Ricorsa infers from your own questions.</p>
    <h2>How the identity graph is used</h2><p>The graph is folded into the prompts sent on your behalf so answers fit what you are working on, and into the ideas Discover proposes and the apps the studio builds for you. It is never shared with other users, never sold, and never used to train models. You can pause learning, forget any node, export the whole graph with its provenance, or reset it at any time from the Graph page. Passages from your own earlier answers and attached files are kept with your account and may be recalled, numbered as sources, into a later answer of yours; they never leave your account, and they go when the conversation they came from is deleted.</p>
    <h2>Processors</h2><p>Answers are generated by a model provider: Moonshot AI (Kimi) by default, and Anthropic (Claude) for the Build studio and Discover ideas; the relevant question text, the retrieved web results, the attached text and your profile summary are sent to the provider that serves that part of Ricorsa to produce the answer, the idea or the app. When a provider cannot serve, another one from the same list takes over for that request; the providers Ricorsa may use are Moonshot AI, Anthropic, OpenAI, Google, xAI, Mistral, DeepSeek, Groq, OpenRouter and Together AI, and only the ones the operator has configured are ever called. Live web results come from Brave Search, which receives the search queries only. Places named in your questions are looked up on a geocoder (OpenStreetMap's Nominatim, or a compatible service the operator configures) so they can be shown on the map in your graph; the geocoder receives the place name only, never your question. Files you attach to a question are read into text on our servers (plain text, code, PDFs, Word, Excel and PowerPoint); scanned documents, images and older binary formats go through Moonshot AI's file extraction service, where the upload is deleted as soon as its text has been read. The text and the file itself are kept with the thread they were used in, in Cloudflare storage in the United States, so you can open the file again in Ricorsa; both are deleted with the thread, and unused uploads are dropped after a day. Your data is stored on Cloudflare. Sign-in is handled by Auth0 and payments by PayPal; we never see your card or bank details.</p>
    <h2>Your rights</h2><p>Export everything from your Account page. Deleting your account removes your data from our systems and cancels any subscription.</p>
  </main><SiteFooter /></>);
}
