import { SiteNav, SiteFooter } from '@/components/SiteNav';
import { viewer } from '@/lib/viewer';
export const metadata = { title: 'Privacy' };
export default async function Privacy() {
  const v = await viewer();
  return (<><SiteNav signedIn={!!v} /><main className="wrap prose">
    <h1>Privacy</h1>
    <p>This is a starting point, not legal advice. Have it reviewed before launch.</p>
    <h2>What we store</h2><p>Your account details from sign-in (name, email), the questions you ask and the answers you receive, your Spaces, your usage counters, and your identity graph: the topics, entities, goals, expertise levels and answer-style preferences that Ricorsa infers from your own questions.</p>
    <h2>How the identity graph is used</h2><p>The graph is folded into the prompts sent on your behalf so answers fit what you are working on. It is never shared with other users, never sold, and never used to train models. You can pause learning, forget any node, export the whole graph, or reset it at any time from the Graph page.</p>
    <h2>Processors</h2><p>Answers and live web results are generated by Anthropic (Claude, including its web search); the relevant question text and your profile summary are sent to Anthropic to produce each answer. Your data is stored on Cloudflare. Sign-in is handled by Auth0 and payments by PayPal; we never see your card or bank details.</p>
    <h2>Your rights</h2><p>Export everything from your Account page. Deleting your account removes your data from our systems and cancels any subscription.</p>
  </main><SiteFooter /></>);
}
